FORMAT: 1A
HOST: https://stock.services.viaaurea.eu/stock/api/

# Skladové zásoby

Služba pro práci se skladovými zásobami na eshopech. Umožňuje...

## Inbound [/inbound/]

Naskladnění

### Vytvoření [POST]

Endpoint slouží pro vytvoření skladových zásob.  (toto netestovat)

```
name 
```
aa


+ Request (application/json)

        [
            {
              "name":"Název přepravy",
              "warehouse":"Brno",
              "client":"Via Aurea",
              "status":"acceptedAAA",
              "identifier": "ASN 2021-03-07-00001",
              "data": "{}",
              "items": [
                {
                  "sku": "PEN_001",
                  "qty": 20,
                  "purchasePrice": 12.898,
                  "currency": "CZK"
                },
                {
                  "sku": "PEN_001",
                  "qty": 10,
                  "purchasePrice": 13.598,
                  "currency": "CZK"
                },
                {
                  "sku": "PEN_002",
                  "qty": 115,
                  "purchasePrice": 102.015,
                  "currency": "CZK"
                }
              ]
            }

        ]
+ Response 200 (application/json)
    
        [
            {
                "date": "2021-"
            }
        ]

+ Response 500 (application/json)

        [
            {
                "errorr": {
                    "message": "Chyba"
                }
            }
        ]

## Movement [/movement/{sku}/]
`sku := PEN_001`

Log pohybů skladových zásob `sku`. Pro stránkování lze použít objekt `paginator`. Pro filtraci lze požít 
objekt `query`.

### List [GET]


+ Response 200 (application/json)

        [
            {
              "data": {
                "date": "2021-03-17T12:47:16.223940Z",
                "items": [
                    {
                        "date":{"date": "2021-03-16 13:36:46.000000", "timezone_type": 3, "timezone": "UTC"},
                        "sku": "PEN_001",
                        "qtyAbsolute": null,
                        "qtyRelative": 20,
                        "warehouse": "Brno",
                        "client": "Via Aurea",
                        "inboundId": 38,
                        "outboundId": null,
                        "note": null
                    },
                    {
                        "date":{"date": "2021-03-16 15:36:13.000000", "timezone_type": 3, "timezone": "UTC"},
                        "sku": "PEN_001",
                        "qtyAbsolute": null,
                        "qtyRelative": -2,
                        "warehouse": "Brno",
                        "client": "Via Aurea",
                        "inboundId": null,
                        "outboundId": 96,
                        "note": "Create outbound"
                    }
                ]
              },
              "meta": {
                "paginator": {
                  "itemsPerPage": 100,
                  "page": 1,
                  "count": 0
                },
                "query": []
              }
            }
        ]


## Stock [/stock/aggregate/]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }